# r_utilities.R -- reusable R helpers for the transfer-dyad analysis.
# Source this file (source("r_utilities.R")); it defines functions only and has no side effects.

# Transfer-dyad data dictionary.
# Convention: from<Name> = sending hospital / origin claim; to<Name> = receiving hospital / destination claim
# (same beneficiary on both sides). *_DAY / *_MONTH are cumulative counters across study years; *_YEAR is calendar year.
get_data_dictionary <- function() {
  tibble::tribble(
    ~column, ~description,

    # ---- dyad identity & keys ----
    "dyad",            "Transfer-pair key: array [fromORGNPINM, toORGNPINM, fromTHRU_DT_YEAR] (direction-aware)",
    "ORGNPINM",        "Hospital organization NPI",
    "DSYSRTKY",        "Beneficiary ID (same person on both sides)",
    "CLAIMNO",         "Claim number (unique with DSYSRTKY + THRU_DT)",
    "PROVIDER",        "Provider CCN",

    # ---- dates / stay length ----
    "THRU_DT",         "Raw claim through-date (YYYYMMDD)",
    "THRU_DT_YEAR",    "Through-date calendar year (from-side is the dyad's reference year)",
    "THRU_DT_MONTH",   "Through-date as cumulative month number across study years",
    "THRU_DT_DAY",     "Through-date as cumulative day number across study years",
    "ADMSN_DT",        "Raw admission date",
    "ADMSN_DT_YEAR",   "Admission calendar year",
    "ADMSN_DT_MONTH",  "Admission as cumulative month number",
    "ADMSN_DT_DAY",    "Admission as cumulative day number",
    "DSCHRGDT",        "Raw discharge date",
    "DSCHRGDT_YEAR",   "Discharge calendar year",
    "DSCHRGDT_DAY",    "Discharge as cumulative day number",
    "DOB_DT",          "Date of birth",
    "los",             "Length of stay in days (through-day - admission-day + 1)",

    # ---- claim attributes ----
    "CLM_TYPE",        "CMS claim type code",
    "FAC_TYPE",        "Facility type code (1=hospital)",
    "TYPESRVC",        "Type-of-service code",
    "PPS_IND",         "Prospective Payment System indicator",
    "TYPE_ADM",        "Admission type code",
    "SRC_ADMS",        "Source of admission (4=transfer from another hospital)",
    "STUS_CD",         "Discharge/patient status (1=routine home, 2=to short-term hosp, 20=died; etc.)",
    "PTNTSTUS",        "Patient discharge status code (string)",
    "DRGWTAMT",        "DRG weight amount",
    "DRG_CD",          "Diagnosis Related Group code",
    "OUTLR_CD",        "Outlier code",
    "GNRL_CNTL_TYPE_CD","General control/ownership type code",
    "CWF_BENE_MDCR_STUS_CD","Beneficiary Medicare status code",

    # ---- diagnoses / present-on-admission ----
    "ADMTG_DGNS_CD",   "Admitting diagnosis (ICD-10)",
    "PRNCPAL_DGNS_CD", "Principal diagnosis (ICD-10)",
    "shockPoa",        "Shock present-on-admission (0/1)",
    "acuteRespiratoryFailurePoa","Acute respiratory failure POA (0/1)",
    "acuteNeurologicalFailurePoa","Acute neurological failure POA (0/1)",
    "coagulopathyPoa", "Coagulopathy POA (0/1)",
    "acuteHepaticInjuryFailurePoa","Acute hepatic injury/failure POA (0/1)",
    "acuteRenalInjuryFailurePoa","Acute renal injury/failure POA (0/1)",
    "acidosisPoa",     "Acidosis POA (0/1)",
    "acuteOrganFailurePoa","Any acute organ-failure POA flag (0/1)",

    # ---- patient demographics ----
    "GNDR_CD",         "Sex code (1=male, 2=female)",
    "RACE_CD",         "CMS race code (0=unknown,1=white,2=black,3=other,4=Asian,5=Hispanic,6=N.Am.native)",

    # ---- geography (beneficiary & raw claim) ----
    "CNTY_CD",         "County code (raw claim)",
    "STATE_CD",        "State code (raw claim)",
    "PRSTATE",         "Provider state",
    "fipsCounty",      "Beneficiary FIPS county code",
    "ssaCounty",       "Beneficiary SSA county code (STATE_CD+CNTY_CD)",
    "fipsState",       "Beneficiary FIPS state (first 2 of fipsCounty)",
    "rucc",            "Beneficiary-county RUCC 2013 (1-9)",
    "region",          "Beneficiary US region (1=NE,2=MW,3=S,4=W)",

    # ---- provider identity / taxonomy / AHA ----
    "providerFIPS",    "Provider FIPS county (from POS file)",
    "providerName",    "Facility name",
    "providerOtherName","Alternate facility name",
    "providerAddress", "Facility street address",
    "providerZip",     "Facility ZIP",
    "providerState",   "Facility state",
    "providerStateFIPS","Facility state FIPS",
    "providerCountyName","Provider county name",
    "providerRegion",  "Provider US census region",
    "providerPrimaryTaxonomy","Provider primary NUCC taxonomy code",
    "gachPrimary",     "General acute-care hospital by primary taxonomy (0/1)",
    "gachAll",         "General acute-care hospital by any taxonomy (0/1)",
    "rachPrimary",     "Rural acute-care hospital by primary taxonomy (0/1)",
    "rachAll",         "Rural acute-care hospital by any taxonomy (0/1)",
    "cahPrimary",      "Critical-access hospital by primary taxonomy (0/1)",
    "cahAll",          "Critical-access hospital by any taxonomy (0/1)",
    "posCah",          "Critical-access flag from POS file (0/1)",
    "posIsRural",      "Rural flag from POS file (0=urban,1=rural)",
    "ccnCah",          "CAH flag derived from CCN range",
    "hospitalFromClaim","1 if claim facility type = hospital, else 0",
    "providerRucc",    "Provider Rural-Urban Continuum Code (1-9)",
    "providerRuccGroup","RUCC grouped (0=1-3 metro,1=4-6 nonmetro adj,2=7-9 nonmetro non-adj)",
    "providerMaPenetration","County Medicare Advantage penetration (%)",
    "providerRuralVersusUrbanIsRural","Rural flag from cost reports (0=urban,1=rural)",
    "providerNumberOfBeds","Licensed bed count",
    "providerNumberOfBedsGroup","Bed-size group (0=<100,1=100-399,2=>=400)",
    "providerNumberOfResidents","Number of residents/interns",
    "ahaProviderLat",  "AHA latitude",
    "ahaProviderLong", "AHA longitude",
    "ahaCah",          "AHA critical-access flag (0/1)",
    "ahaTelestrokeHos","AHA telestroke at hospital level (0/1; NULL pre-2017)",
    "ahaTelestrokeSys","AHA telestroke at system level (0/1; NULL pre-2017)",
    "ahaTelestrokeVen","AHA telestroke via joint venture (0/1; NULL pre-2017)",
    "ahaTeleicuHos",   "AHA teleICU at hospital level (0/1; NULL pre-2017)",
    "ahaTeleicuSys",   "AHA teleICU at system level (0/1; NULL pre-2017)",
    "ahaTeleicuVen",   "AHA teleICU via joint venture (0/1; NULL pre-2017)",
    "ahaBeds",         "AHA total facility beds",
    "ahaSize",         "AHA bed-size category (0=<100,1=100-399,2=>=400, NULL=missing)",
    "ahaOwner",        "Ownership (0=govt non-fed,1=nonprofit,2=for-profit,3=govt federal)",
    "ahaCbsaType",     "CBSA type (0=metro,1=micro,2=rural)",
    "ahaNisTeachingHospital","NIS teaching hospital (1 if COTH/ACGME/resident-to-bed>=0.25)",
    "ahaResidentToBedRatio","FTE residents-to-beds ratio",
    "ahaBedsIcu",      "Medical/surgical ICU bed count (AHA)",
    "ahaBedsIcuPrior", "Prior-year ICU bed count (AHA)",
    "ahaSystemMember", "AHA health-system member (1 if MHSMEMB=1, else 0)",
    "ahaSystemMemberId","AHA system identifier (last 4 digits of SYSID)",
    "providerSysId",   "Provider system ID (SYSID)",
    "providerIsVI",    "Vertically integrated / in a health system (0/1, from CHSP)",
    "providerCmi",     "Case-mix index",

    # ---- MBSF beneficiary / county context ----
    "mbsfFipsCounty",  "Beneficiary residence FIPS county (MBSF)",
    "mbsfAge",         "Beneficiary age (MBSF, year-end/at death)",
    "ffsFirstMonth",   "First month of FFS eligibility (cumulative; NULL if never FFS)",
    "mbsfAnyEsrd",     "Any ESRD indicator (0/1)",
    "medicaidEver",    "Medicaid dual-eligible any month that year (0/1)",
    "mbsfSex",         "MBSF sex (1=male,2=female)",
    "mbsfRace",        "MBSF race (1=white,2=black,3=other)",
    "mbsfRucc",        "Beneficiary-county RUCC 2013 (1-6 collapsed scale)",
    "mbsfRegion",      "Beneficiary US region (1=NE,2=MW,3=S,4=W)",
    "mbsfMaPenetration","Beneficiary-county MA penetration (proportion)",
    "mbsfMeanContinuousFfsAndRfrncYrForCountyYear","County-year mean proportion with continuous FFS + reference-year coverage",
    "mbsfMedianHhIncome","County median household income ($, nominal)",
    "mbsfMedianHhIncomeAdjusted","County median household income (inflation-adjusted)",
    "mbsfMedianDistanceEd","County median distance (mi) to nearest ED",
    "mbsfMedianDistanceIcu","County median distance (mi) to nearest ICU",
    "mbsfMedianDistanceTrauma","County median distance (mi) to nearest trauma center",

    # ---- mortality ----
    "DEATH_DT_YEAR",   "Year of (validated) death; NULL if alive",
    "DEATH_DT_DAY",    "Death as cumulative day number; NULL if alive",
    "DEATH_DT",        "Raw validated death date; NULL if alive/unvalidated",
    "daysDeadAfterThroughDate","Days from through-date to death (neg if before)",
    "90DaysAfterThroughDateDead","Died within 90d of through-date (0/1)",
    "365DaysAfterThroughDateDead","Died within 365d of through-date (0/1)",
    "daysDeadAfterAdmissionDate","Days from admission to death",
    "30DaysAfterAdmissionDateDead","Died within 30d of admission (0/1)",
    "90DaysAfterAdmissionDateDead","Died within 90d of admission (0/1)",
    "365DaysAfterAdmissionDateDead","Died within 365d of admission (0/1)",

    # ---- revenue-center flags ----
    "ed",              "Emergency-dept revenue center present (0/1)",
    "mri",             "MRI revenue center present (0/1)",
    "ct",              "CT revenue center present (0/1)",
    "icu",             "ICU revenue center present (0/1)",
    "prior",           "Prior-year value of the associated claim/revenue flag (lag by provider/year)",

    # ---- procedures / outcomes (receiving claim only) ----
    "ecmo",            "ECMO performed (0/1)",
    "rrt",             "RRT performed (0/1)",
    "endoscopy",       "Endoscopy performed (0/1)",
    "majorDiagnosticOrTherapeuticOrProcedures","Any HCUP class 3/4 major OR procedure (0/1)",
    "diedInVisit",     "Died during the stay (STUS_CD=20) (0/1)",
    "dischargeHomeWithin2Days","Discharged home (STUS_CD=1) with LOS<=2 days (0/1)",

    # ---- provider capability / volume (sepsis-shock cohort) ----
    "providerSepticShockVol","Hospital septic-shock case volume that year",
    "providerSepticShockVolPrior","Hospital prior-year septic-shock volume",
    "providerImvCapability","Hospital invasive mechanical ventilation capability that year (0/1)",
    "providerImvCapabilityPrior","Hospital prior-year IMV capability (0/1)",
    "providerRrtCapability","Hospital renal replacement therapy capability that year (0/1)",
    "providerRrtCapabilityPrior","Hospital prior-year RRT capability (0/1)",
    "providerMajorDiagnosticOrTherapeuticOrProceduresCapability","Hospital major OR-procedure capability that year (0/1)",
    "providerMajorDiagnosticOrTherapeuticOrProceduresCapabilityPrior","Hospital prior-year major OR-procedure capability (0/1)",

    # ---- transfer network: node & dyad metrics ----
    "firstTransfer",   "1 if this is the patient's earliest transfer (min from-through-day), else 0",
    "nodeOutVol",      "Sending hospital: total transfers sent out that year",
    "nodeInVol",       "Receiving hospital: total transfers received that year",
    "nodeFromSetOfToNodes","Sending hospital: array of distinct destination NPIs that year",
    "nodeFromSizeOfToNodes","Sending hospital: count of distinct destinations that year",
    "nodeToSetOfFromNodes","Receiving hospital: array of distinct source NPIs that year",
    "nodeToSizeOfFromNodes","Receiving hospital: count of distinct sources that year",
    "nodeFromEdVol",   "Sending hospital: sum of ED flags over its outgoing transfers",
    "nodeFromEdMean",  "Sending hospital: mean ED flag over its outgoing transfers",
    "nodeFromCtVol",   "Sending hospital: sum of CT flags over its outgoing transfers",
    "nodeFromCtMean",  "Sending hospital: mean CT flag over its outgoing transfers",
    "nodeFromMriVol",  "Sending hospital: sum of MRI flags over its outgoing transfers",
    "nodeFromMriMean", "Sending hospital: mean MRI flag over its outgoing transfers",
    "nodeToEdVol",     "Receiving hospital: sum of ED flags over its incoming transfers",
    "nodeToEdMean",    "Receiving hospital: mean ED flag over its incoming transfers",
    "nodeToCtVol",     "Receiving hospital: sum of CT flags over its incoming transfers",
    "nodeToCtMean",    "Receiving hospital: mean CT flag over its incoming transfers",
    "nodeToMriVol",    "Receiving hospital: sum of MRI flags over its incoming transfers",
    "nodeToMriMean",   "Receiving hospital: mean MRI flag over its incoming transfers",
    "dyadVi",          "1 if sending & receiving share the same system (SYSID), else 0",
    "dyadTransferVol", "Number of transfers along this specific dyad (year)",
    "dyadProportionTransfersOut","dyadTransferVol / sending hospital's nodeOutVol",
    "dyadProportionTransfersIn","dyadTransferVol / receiving hospital's nodeInVol",
    "dyadProportionTransfersOutPrior","Prior-year value of dyadProportionTransfersOut",
    "dyadProportionTransfersInPrior","Prior-year value of dyadProportionTransfersIn",
    "dyadAcrossCounties","1 if sending & receiving in different counties, 0 same (NULL if missing)",
    "dyadAcrossStates","1 if sending & receiving in different states, 0 same (NULL if missing)",
    "nodeHhi",         "Sending hospital: Herfindahl index of outgoing-transfer concentration (1=all to one dest)",
    "nodeHhiPrior",    "Prior-year value of nodeHhi",
    "prior (network)", "Prior-year marker used by the network *Prior lags (1-year lag); distinct from the from/to claim 'prior'",

    # ---- patient comorbidity & hospitalization history (transferred beneficiary) ----
    "hospitalizationsIn12Months","Count of inpatient stays in prior 365 days (NULL if <12mo enrollment)",
    "hospitalizedIn12Months","1 if >=1 inpatient stay in prior 12 months, else 0",
    "hospitalizationsIn6Months","Count of inpatient stays in prior 182 days (NULL if <6mo enrollment)",
    "hospitalizedIn6Months","1 if >=1 inpatient stay in prior 6 months, else 0",
    "myocardialInfraction","Myocardial infarction (0/1) [sic spelling]",
    "congestiveHeartFailure","Congestive heart failure (0/1)",
    "peripheralVascular","Peripheral vascular disease (0/1)",
    "cerebrovascular", "Cerebrovascular disease (0/1)",
    "dementia",        "Dementia (0/1)",
    "chronicPulmonary","Chronic pulmonary disease (0/1)",
    "rheumatic",       "Rheumatic disease (0/1)",
    "pepticUlcer",     "Peptic ulcer disease (0/1)",
    "liverMild",       "Mild liver disease (0/1; zeroed if liverSevere=1)",
    "diabetesWithoutCC","Diabetes without complications (0/1)",
    "renalMild",       "Mild renal disease (0/1; zeroed if renalSevere=1)",
    "diabetesWithCC",  "Diabetes with complications (0/1)",
    "hemiplegia",      "Hemiplegia/paraplegia (0/1)",
    "malignancy",      "Malignancy (0/1; zeroed if metastaticSolidTumor=1)",
    "liverSevere",     "Severe liver disease (0/1)",
    "renalSevere",     "Severe renal disease (0/1)",
    "hiv",             "HIV (0/1; zeroed if aids=1)",
    "metastaticSolidTumor","Metastatic solid tumor (0/1)",
    "aids",            "AIDS (0/1)",
    "comorbityIndex",  "Glasheen-2019 weighted comorbidity index (numeric) [sic spelling]"
  )
}
