from pyspark.sql.types import StructType, StructField, StringType, IntegerType, LongType, DoubleType

carBaseSchema = StructType([
    StructField('DESY_SORT_KEY', IntegerType(), True), 
    StructField('CLAIM_NO', IntegerType(), True), 
    StructField('CLM_THRU_DT', IntegerType(), True), 
    StructField('NCH_NEAR_LINE_REC_IDENT_CD', StringType(), True), 
    StructField('NCH_CLM_TYPE_CD', IntegerType(), True), 
    StructField('CLM_DISP_CD', IntegerType(), True),
    StructField('CARR_NUM', IntegerType(), True), 
    StructField('CARR_CLM_PMT_DNL_CD', StringType(), True), 
    StructField('CLM_PMT_AMT', DoubleType(), True), 
    StructField('CARR_CLM_PRMRY_PYR_PD_AMT', DoubleType(), True), 
    StructField('RFR_PHYSN_UPIN', StringType(), True), 
    StructField('RFR_PHYSN_NPI', IntegerType(), True), 
    StructField('CARR_CLM_PRVDR_ASGNMT_IND_SW', StringType(), True),
    StructField('NCH_CLM_PRVDR_PMT_AMT', DoubleType(), True), 
    StructField('NCH_CLM_BENE_PMT_AMT', DoubleType(), True), 
    StructField('NCH_CARR_CLM_SBMTD_CHRG_AMT', DoubleType(), True), 
    StructField('NCH_CARR_CLM_ALOWD_AMT', DoubleType(), True), 
    StructField('CARR_CLM_CASH_DDCTBL_APLD_AMT', DoubleType(), True), 
    StructField('CARR_CLM_HCPCS_YR_CD', IntegerType(), True), 
    StructField('CARR_CLM_RFRNG_PIN_NUM', StringType(), True), 
    StructField('PRNCPAL_DGNS_CD', StringType(), True), 
    StructField('PRNCPAL_DGNS_VRSN_CD', StringType(), True), 
    StructField('ICD_DGNS_CD1', StringType(), True), 
    StructField('ICD_DGNS_VRSN_CD1', IntegerType(), True), 
    StructField('ICD_DGNS_CD2', StringType(), True),
    StructField('ICD_DGNS_VRSN_CD2', IntegerType(), True), 
    StructField('ICD_DGNS_CD3', StringType(), True), 
    StructField('ICD_DGNS_VRSN_CD3', IntegerType(), True), 
    StructField('ICD_DGNS_CD4', StringType(), True), 
    StructField('ICD_DGNS_VRSN_CD4', IntegerType(), True), 
    StructField('ICD_DGNS_CD5', StringType(), True), 
    StructField('ICD_DGNS_VRSN_CD5', IntegerType(), True), 
    StructField('ICD_DGNS_CD6', StringType(), True), 
    StructField('ICD_DGNS_VRSN_CD6', IntegerType(), True), 
    StructField('ICD_DGNS_CD7', StringType(), True), 
    StructField('ICD_DGNS_VRSN_CD7', IntegerType(), True), 
    StructField('ICD_DGNS_CD8', StringType(), True), 
    StructField('ICD_DGNS_VRSN_CD8', IntegerType(), True),
    StructField('ICD_DGNS_CD9', StringType(), True), 
    StructField('ICD_DGNS_VRSN_CD9', IntegerType(), True), 
    StructField('ICD_DGNS_CD10', StringType(), True), 
    StructField('ICD_DGNS_VRSN_CD10', IntegerType(), True), 
    StructField('ICD_DGNS_CD11', StringType(), True), 
    StructField('ICD_DGNS_VRSN_CD11', IntegerType(), True), 
    StructField('ICD_DGNS_CD12', StringType(), True), 
    StructField('ICD_DGNS_VRSN_CD12', IntegerType(), True),
    StructField('DOB_DT', IntegerType(), True), 
    StructField('GNDR_CD', IntegerType(), True), 
    StructField('BENE_RACE_CD', IntegerType(), True), 
    StructField('BENE_CNTY_CD', StringType(), True), 
    StructField('BENE_STATE_CD', StringType(), True), 
    StructField('CWF_BENE_MDCR_STUS_CD', IntegerType(), True), 
    StructField('CLM_BENE_PD_AMT', DoubleType(), True), 
    StructField('CPO_PRVDR_NUM', IntegerType(), True), 
    StructField('CPO_ORG_NPI_NUM', IntegerType(), True), 
    StructField('CARR_CLM_BLG_NPI_NUM', IntegerType(), True), 
    StructField('ACO_ID_NUM', IntegerType(), True)])

carBaseLongToShortXW = {'DESY_SORT_KEY': "DSYSRTKY",
 'CLAIM_NO': "CLAIMNO",
 'CLM_THRU_DT': "THRU_DT",
 'NCH_NEAR_LINE_REC_IDENT_CD': "RIC_CD",
 'NCH_CLM_TYPE_CD': "CLM_TYPE",
 'CLM_DISP_CD': "DISP_CD",
 'CARR_NUM': "CARR_NUM",
 'CARR_CLM_PMT_DNL_CD': "PMTDNLCD",
 'CLM_PMT_AMT': "PMT_AMT",
 'CARR_CLM_PRMRY_PYR_PD_AMT': "PRPAYAMT",
 'RFR_PHYSN_UPIN': "RFR_UPIN",
 'RFR_PHYSN_NPI': "RFR_NPI",
 'CARR_CLM_PRVDR_ASGNMT_IND_SW': "ASGMNTCD",
 'NCH_CLM_PRVDR_PMT_AMT': "PROV_PMT",
 'NCH_CLM_BENE_PMT_AMT': "BENE_PMT",
 'NCH_CARR_CLM_SBMTD_CHRG_AMT': "SBMTCHRG",
 'NCH_CARR_CLM_ALOWD_AMT': "ALOWCHRG",
 'CARR_CLM_CASH_DDCTBL_APLD_AMT': "DEDAPPLY",
 'CARR_CLM_HCPCS_YR_CD': "HCPCS_YR",
 'CARR_CLM_RFRNG_PIN_NUM': "RFR_PRFL",
 'PRNCPAL_DGNS_CD': "PRNCPAL_DGNS_CD",
 'PRNCPAL_DGNS_VRSN_CD': "PRNCPAL_DGNS_VRSN_CD",
 'ICD_DGNS_CD1': "ICD DGNS CD1",
 'ICD_DGNS_VRSN_CD1': "ICD DGNS VRSN CD1",
 'ICD_DGNS_CD2': "ICD DGNS CD2",
 'ICD_DGNS_VRSN_CD2': "ICD DGNS VRSN CD2",
 'ICD_DGNS_CD3': "ICD DGNS CD3",
 'ICD_DGNS_VRSN_CD3': "ICD DGNS VRSN CD3",
 'ICD_DGNS_CD4': "ICD DGNS CD4",
 'ICD_DGNS_VRSN_CD4': "ICD DGNS VRSN CD4",
 'ICD_DGNS_CD5': "ICD DGNS CD5",
 'ICD_DGNS_VRSN_CD5': "ICD DGNS VRSN CD5",
 'ICD_DGNS_CD6': "ICD DGNS CD6",
 'ICD_DGNS_VRSN_CD6': "ICD DGNS VRSN CD6",
 'ICD_DGNS_CD7': "ICD DGNS CD7",
 'ICD_DGNS_VRSN_CD7': "ICD DGNS VRSN CD7",
 'ICD_DGNS_CD8': "ICD DGNS CD8",
 'ICD_DGNS_VRSN_CD8': "ICD DGNS VRSN CD8",
 'ICD_DGNS_CD9': "ICD DGNS CD9",
 'ICD_DGNS_VRSN_CD9': "ICD DGNS VRSN CD9",
 'ICD_DGNS_CD10': "ICD DGNS CD10",
 'ICD_DGNS_VRSN_CD10': "ICD DGNS VRSN CD10",
 'ICD_DGNS_CD11': "ICD DGNS CD11",
 'ICD_DGNS_VRSN_CD11': "ICD DGNS VRSN CD11",
 'ICD_DGNS_CD12': "ICD DGNS CD12",
 'ICD_DGNS_VRSN_CD12': "ICD DGNS VRSN CD12",
 'DOB_DT': "DOB_DT",
 'GNDR_CD': "GNDR_CD",
 'BENE_RACE_CD': "RACE_CD",
 'BENE_CNTY_CD': "CNTY_CD",
 'BENE_STATE_CD': "STATE_CD",
 'CWF_BENE_MDCR_STUS_CD': "CWF_BENE_MDCR_STUS_CD",
 'CLM_BENE_PD_AMT': "CLM_BENE_PD_AMT",
 'CPO_PRVDR_NUM': "CPO_PRVDR_NUM",
 'CPO_ORG_NPI_NUM': "CPO_ORG_NPI_NUM",
 'CARR_CLM_BLG_NPI_NUM': "CARR_CLM_BLG_NPI_NUM",
 'ACO_ID_NUM': "ACO_ID_NUM"}

carLineSchema = StructType([
    StructField('DESY_SORT_KEY', IntegerType(), True), 
    StructField('CLAIM_NO', IntegerType(), True), 
    StructField('LINE_NUM', IntegerType(), True), 
    StructField('CLM_THRU_DT', IntegerType(), True), 
    StructField('NCH_CLM_TYPE_CD', IntegerType(), True), 
    StructField('CARR_PRFRNG_PIN_NUM', StringType(), True), 
    StructField('PRF_PHYSN_UPIN', IntegerType(), True), 
    StructField('PRF_PHYSN_NPI', IntegerType(), True), 
    StructField('ORG_NPI_NUM', IntegerType(), True), 
    StructField('CARR_LINE_PRVDR_TYPE_CD', IntegerType(), True),
    StructField('PRVDR_STATE_CD', StringType(), True), 
    StructField('PRVDR_SPCLTY', IntegerType(), True), 
    StructField('PRTCPTNG_IND_CD', IntegerType(), True), 
    StructField('CARR_LINE_RDCD_PMT_PHYS_ASTN_C', IntegerType(), True), 
    StructField('LINE_SRVC_CNT', IntegerType(), True), 
    StructField('LINE_CMS_TYPE_SRVC_CD', StringType(), True), 
    StructField('LINE_PLACE_OF_SRVC_CD', StringType(), True), 
    StructField('CARR_LINE_PRCNG_LCLTY_CD', IntegerType(), True), 
    StructField('LINE_LAST_EXPNS_DT', IntegerType(), True), 
    StructField('HCPCS_CD', StringType(), True), 
    StructField('HCPCS_1ST_MDFR_CD', StringType(), True), 
    StructField('HCPCS_2ND_MDFR_CD', StringType(), True),
    StructField('BETOS_CD', StringType(), True), 
    StructField('LINE_NCH_PMT_AMT', DoubleType(), True), 
    StructField('LINE_BENE_PMT_AMT', DoubleType(), True), 
    StructField('LINE_PRVDR_PMT_AMT', DoubleType(), True),
    StructField('LINE_BENE_PTB_DDCTBL_AMT', DoubleType(), True), 
    StructField('LINE_BENE_PRMRY_PYR_CD', StringType(), True), 
    StructField('LINE_BENE_PRMRY_PYR_PD_AMT', DoubleType(), True), 
    StructField('LINE_COINSRNC_AMT', DoubleType(), True), 
    StructField('LINE_SBMTD_CHRG_AMT', DoubleType(), True), 
    StructField('LINE_ALOWD_CHRG_AMT', DoubleType(), True), 
    StructField('LINE_PRCSG_IND_CD', StringType(), True), 
    StructField('LINE_PMT_80_100_CD', IntegerType(), True), 
    StructField('LINE_SERVICE_DEDUCTIBLE', IntegerType(), True), 
    StructField('CARR_LINE_MTUS_CNT', IntegerType(), True), 
    StructField('CARR_LINE_MTUS_CD', StringType(), True), 
    StructField('LINE_ICD_DGNS_CD', StringType(), True), 
    StructField('LINE_ICD_DGNS_VRSN_CD', IntegerType(), True), 
    StructField('LINE_HCT_HGB_RSLT_NUM', StringType(), True), 
    StructField('LINE_HCT_HGB_TYPE_CD', StringType(), True), 
    StructField('LINE_NDC_CD', StringType(), True), 
    StructField('CARR_LINE_CLIA_LAB_NUM', StringType(), True), 
    StructField('CARR_LINE_ANSTHSA_UNIT_CNT', IntegerType(), True), 
    StructField('CARR_LINE_CL_CHRG_AMT', DoubleType(), True), 
    StructField('LINE_OTHR_APLD_IND_CD1', StringType(), True), 
    StructField('LINE_OTHR_APLD_IND_CD2', StringType(), True), 
    StructField('LINE_OTHR_APLD_IND_CD3', StringType(), True), 
    StructField('LINE_OTHR_APLD_IND_CD4', StringType(), True), 
    StructField('LINE_OTHR_APLD_IND_CD5', StringType(), True), 
    StructField('LINE_OTHR_APLD_IND_CD6', StringType(), True), 
    StructField('LINE_OTHR_APLD_IND_CD7', StringType(), True), 
    StructField('LINE_OTHR_APLD_AMT1', DoubleType(), True), 
    StructField('LINE_OTHR_APLD_AMT2', DoubleType(), True), 
    StructField('LINE_OTHR_APLD_AMT3', DoubleType(), True), 
    StructField('LINE_OTHR_APLD_AMT4', DoubleType(), True), 
    StructField('LINE_OTHR_APLD_AMT5', DoubleType(), True), 
    StructField('LINE_OTHR_APLD_AMT6', DoubleType(), True), 
    StructField('LINE_OTHR_APLD_AMT7', DoubleType(), True), 
    StructField('THRPY_CAP_IND_CD1', StringType(), True), 
    StructField('THRPY_CAP_IND_CD2', StringType(), True), 
    StructField('THRPY_CAP_IND_CD3', StringType(), True), 
    StructField('THRPY_CAP_IND_CD4', StringType(), True), 
    StructField('THRPY_CAP_IND_CD5', StringType(), True), 
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD1', IntegerType(), True), 
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD2', IntegerType(), True), 
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD3', IntegerType(), True), 
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD4', IntegerType(), True), 
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD5', IntegerType(), True)])

carLineLongToShortXW = {'DESY_SORT_KEY':"DSYSRTKY",
 'CLAIM_NO':"CLAIMNO",
 'LINE_NUM':"CLM_LN",
 'CLM_THRU_DT':"THRU_DT",
 'NCH_CLM_TYPE_CD':"CLM_TYPE",
 'CARR_PRFRNG_PIN_NUM':"PRF_PRFL",
 'PRF_PHYSN_UPIN':"PRF_UPIN",
 'PRF_PHYSN_NPI':"PRF_NPI",
 'ORG_NPI_NUM':"PRGRPNPI",
 'CARR_LINE_PRVDR_TYPE_CD':"PRV_TYPE",
 'PRVDR_STATE_CD':"PRVSTATE",
 'PRVDR_SPCLTY':"HCFASPCL",
 'PRTCPTNG_IND_CD':"PRTCPTG",
 'CARR_LINE_RDCD_PMT_PHYS_ASTN_C':"ASTNT_CD",
 'LINE_SRVC_CNT':"SRVC_CNT",
 'LINE_CMS_TYPE_SRVC_CD':"TYPSRVCB",
 'LINE_PLACE_OF_SRVC_CD':"PLCSRVC",
 'CARR_LINE_PRCNG_LCLTY_CD':"LCLTY_CD",
 'LINE_LAST_EXPNS_DT':"EXPNSDT2",
 'HCPCS_CD':"HCPCS_CD",
 'HCPCS_1ST_MDFR_CD':"MDFR_CD1",
 'HCPCS_2ND_MDFR_CD':"MDFR_CD2",
 'BETOS_CD':"BETOS",
 'LINE_NCH_PMT_AMT':"LINEPMT",
 'LINE_BENE_PMT_AMT':"LBENPMT",
 'LINE_PRVDR_PMT_AMT':"LPRVPMT",
 'LINE_BENE_PTB_DDCTBL_AMT':"LDEDAMT",
 'LINE_BENE_PRMRY_PYR_CD':"LPRPAYCD",
 'LINE_BENE_PRMRY_PYR_PD_AMT':"LPRPDAMT",
 'LINE_COINSRNC_AMT':"COINAMT",
 'LINE_SBMTD_CHRG_AMT':"LSBMTCHG",
 'LINE_ALOWD_CHRG_AMT':"LALOWCHG",
 'LINE_PRCSG_IND_CD':"PRCNGIND",
 'LINE_PMT_80_100_CD':"PMTINDSW",
 'LINE_SERVICE_DEDUCTIBLE':"DED_SW",
 'CARR_LINE_MTUS_CNT':"MTUS_CNT",
 'CARR_LINE_MTUS_CD':"MTUS_IND",
 'LINE_ICD_DGNS_CD':"LINE_ICD_DGNS_CD",
 'LINE_ICD_DGNS_VRSN_CD':"LINE_ICD_DGNS_VRSN_CD",
 'LINE_HCT_HGB_RSLT_NUM':"HCTHGBRS",
 'LINE_HCT_HGB_TYPE_CD':"HCTHGBTP",
 'LINE_NDC_CD':"LNNDCCD",
 'CARR_LINE_CLIA_LAB_NUM':"CARR_LINE_CLIA_LAB_NUM",
 'CARR_LINE_ANSTHSA_UNIT_CNT':"CARR_LINE_ANSTHSA_UNIT_CNT",
 'CARR_LINE_CL_CHRG_AMT':"CARR_LINE_CL_CHRG_AMT",
 'LINE_OTHR_APLD_IND_CD1':"LINE_OTHR_APLD_IND_CD1",
 'LINE_OTHR_APLD_IND_CD2':"LINE_OTHR_APLD_IND_CD2",
 'LINE_OTHR_APLD_IND_CD3':"LINE_OTHR_APLD_IND_CD3",
 'LINE_OTHR_APLD_IND_CD4':"LINE_OTHR_APLD_IND_CD4",
 'LINE_OTHR_APLD_IND_CD5':"LINE_OTHR_APLD_IND_CD5",
 'LINE_OTHR_APLD_IND_CD6':"LINE_OTHR_APLD_IND_CD6",
 'LINE_OTHR_APLD_IND_CD7':"LINE_OTHR_APLD_IND_CD7",
 'LINE_OTHR_APLD_AMT1':"LINE_OTHR_APLD_AMT1",
 'LINE_OTHR_APLD_AMT2':"LINE_OTHR_APLD_AMT2",
 'LINE_OTHR_APLD_AMT3':"LINE_OTHR_APLD_AMT3",
 'LINE_OTHR_APLD_AMT4':"LINE_OTHR_APLD_AMT4",
 'LINE_OTHR_APLD_AMT5':"LINE_OTHR_APLD_AMT5",
 'LINE_OTHR_APLD_AMT6':"LINE_OTHR_APLD_AMT6",
 'LINE_OTHR_APLD_AMT7':"LINE_OTHR_APLD_AMT7",
 'THRPY_CAP_IND_CD1':"THRPY_CAP_IND_CD1",
 'THRPY_CAP_IND_CD2':"THRPY_CAP_IND_CD2",
 'THRPY_CAP_IND_CD3':"THRPY_CAP_IND_CD3",
 'THRPY_CAP_IND_CD4':"THRPY_CAP_IND_CD4",
 'THRPY_CAP_IND_CD5':"THRPY_CAP_IND_CD5",
 'CLM_NEXT_GNRTN_ACO_IND_CD1':"CLM_NEXT_GNRTN_ACO_IND_CD1",
 'CLM_NEXT_GNRTN_ACO_IND_CD2':"CLM_NEXT_GNRTN_ACO_IND_CD2",
 'CLM_NEXT_GNRTN_ACO_IND_CD3':"CLM_NEXT_GNRTN_ACO_IND_CD3",
 'CLM_NEXT_GNRTN_ACO_IND_CD4':"CLM_NEXT_GNRTN_ACO_IND_CD4",
 'CLM_NEXT_GNRTN_ACO_IND_CD5':"CLM_NEXT_GNRTN_ACO_IND_CD5"}
