from pyspark.sql.types import StructType, StructField, StringType, IntegerType, LongType, DoubleType

hhaBaseSchema = StructType([
    StructField('DESY_SORT_KEY', IntegerType(), True), 
    StructField('CLAIM_NO', IntegerType(), True), 
    StructField('PRVDR_NUM', StringType(), True), 
    StructField('CLM_THRU_DT', IntegerType(), True), 
    StructField('NCH_NEAR_LINE_REC_IDENT_CD', StringType(), True), 
    StructField('NCH_CLM_TYPE_CD', IntegerType(), True), 
    StructField('CLM_FAC_TYPE_CD', IntegerType(), True), 
    StructField('CLM_SRVC_CLSFCTN_TYPE_CD', IntegerType(), True), 
    StructField('CLM_FREQ_CD', StringType(), True), 
    StructField('FI_NUM', IntegerType(), True), 
    StructField('CLM_MDCR_NON_PMT_RSN_CD', StringType(), True), 
    StructField('CLM_PMT_AMT', DoubleType(), True), 
    StructField('NCH_PRMRY_PYR_CLM_PD_AMT', DoubleType(), True), 
    StructField('NCH_PRMRY_PYR_CD', StringType(), True), 
    StructField('PRVDR_STATE_CD', StringType(), True), 
    StructField('ORG_NPI_NUM', IntegerType(), True), 
    StructField('SRVC_LOC_NPI_NUM', IntegerType(), True), 
    StructField('AT_PHYSN_UPIN', IntegerType(), True), 
    StructField('AT_PHYSN_NPI', IntegerType(), True), 
    StructField('AT_PHYSN_SPCLTY_CD', IntegerType(), True), 
    StructField('OP_PHYSN_NPI', IntegerType(), True), 
    StructField('OP_PHYSN_SPCLTY_CD', IntegerType(), True), 
    StructField('OT_PHYSN_NPI', IntegerType(), True), 
    StructField('OT_PHYSN_SPCLTY_CD', IntegerType(), True), 
    StructField('RNDRNG_PHYSN_NPI', IntegerType(), True), 
    StructField('RNDRNG_PHYSN_SPCLTY_CD', IntegerType(), True), 
    StructField('RFR_PHYSN_NPI', IntegerType(), True), 
    StructField('RFR_PHYSN_SPCLTY_CD', IntegerType(), True), 
    StructField('PTNT_DSCHRG_STUS_CD', IntegerType(), True), 
    StructField('CLM_PPS_IND_CD', IntegerType(), True), 
    StructField('CLM_TOT_CHRG_AMT', DoubleType(), True), 
    StructField('PRNCPAL_DGNS_CD', StringType(), True), 
    StructField('ICD_DGNS_CD1', StringType(), True), 
    StructField('ICD_DGNS_CD2', StringType(), True), 
    StructField('ICD_DGNS_CD3', StringType(), True), 
    StructField('ICD_DGNS_CD4', StringType(), True), 
    StructField('ICD_DGNS_CD5', StringType(), True), 
    StructField('ICD_DGNS_CD6', StringType(), True), 
    StructField('ICD_DGNS_CD7', StringType(), True), 
    StructField('ICD_DGNS_CD8', StringType(), True), 
    StructField('ICD_DGNS_CD9', StringType(), True),
    StructField('ICD_DGNS_CD10', StringType(), True), 
    StructField('ICD_DGNS_CD11', StringType(), True), 
    StructField('ICD_DGNS_CD12', StringType(), True), 
    StructField('ICD_DGNS_CD13', StringType(), True), 
    StructField('ICD_DGNS_CD14', StringType(), True), 
    StructField('ICD_DGNS_CD15', StringType(), True), 
    StructField('ICD_DGNS_CD16', StringType(), True), 
    StructField('ICD_DGNS_CD17', StringType(), True), 
    StructField('ICD_DGNS_CD18', StringType(), True), 
    StructField('ICD_DGNS_CD19', StringType(), True), 
    StructField('ICD_DGNS_CD20', StringType(), True), 
    StructField('ICD_DGNS_CD21', StringType(), True), 
    StructField('ICD_DGNS_CD22', StringType(), True), 
    StructField('ICD_DGNS_CD23', StringType(), True), 
    StructField('ICD_DGNS_CD24', StringType(), True), 
    StructField('ICD_DGNS_CD25', StringType(), True), 
    StructField('FST_DGNS_E_CD', StringType(), True),
    StructField('ICD_DGNS_E_CD1', StringType(), True), 
    StructField('ICD_DGNS_E_CD2', StringType(), True), 
    StructField('ICD_DGNS_E_CD3', StringType(), True), 
    StructField('ICD_DGNS_E_CD4', StringType(), True), 
    StructField('ICD_DGNS_E_CD5', StringType(), True), 
    StructField('ICD_DGNS_E_CD6', StringType(), True), 
    StructField('ICD_DGNS_E_CD7', StringType(), True), 
    StructField('ICD_DGNS_E_CD8', StringType(), True), 
    StructField('ICD_DGNS_E_CD9', StringType(), True), 
    StructField('ICD_DGNS_E_CD10', StringType(), True),
    StructField('ICD_DGNS_E_CD11', StringType(), True), 
    StructField('ICD_DGNS_E_CD12', StringType(), True), 
    StructField('CLM_HHA_LUPA_IND_CD', StringType(), True), 
    StructField('CLM_HHA_RFRL_CD', StringType(), True), 
    StructField('CLM_HHA_TOT_VISIT_CNT', IntegerType(), True), 
    StructField('CLM_ADMSN_DT', IntegerType(), True), 
    StructField('DOB_DT', IntegerType(), True), 
    StructField('GNDR_CD', IntegerType(), True), 
    StructField('BENE_RACE_CD', IntegerType(), True), 
    StructField('BENE_CNTY_CD', StringType(), True), 
    StructField('BENE_STATE_CD', StringType(), True), 
    StructField('CWF_BENE_MDCR_STUS_CD', IntegerType(), True),
    StructField('CLM_QUERY_CD', IntegerType(), True), 
    StructField('FI_CLM_ACTN_CD', IntegerType(), True), 
    StructField('CLM_MCO_PD_SW', IntegerType(), True), 
    StructField('NCH_BENE_DSCHRG_DT', IntegerType(), True), 
    StructField('CLM_TRTMT_AUTHRZTN_NUM', StringType(), True), 
    StructField('CLM_PRCR_RTRN_CD', IntegerType(), True), 
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD1', IntegerType(), True),
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD2', IntegerType(), True),
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD3', IntegerType(), True), 
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD4', IntegerType(), True), 
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD5', IntegerType(), True), 
    StructField('ACO_ID_NUM', StringType(), True)])

hhaBaseLongToShortXW = {'DESY_SORT_KEY': "DSYSRTKY",
 'CLAIM_NO': "CLAIMNO",
 'PRVDR_NUM': "PROVIDER",
 'CLM_THRU_DT': "THRU_DT",
 'NCH_NEAR_LINE_REC_IDENT_CD': "RIC_CD",
 'NCH_CLM_TYPE_CD': "CLM_TYPE",
 'CLM_FAC_TYPE_CD': "FAC_TYPE",
 'CLM_SRVC_CLSFCTN_TYPE_CD': "TYPESRVC",
 'CLM_FREQ_CD': "FREQ_CD",
 'FI_NUM': "FI_NUM",
 'CLM_MDCR_NON_PMT_RSN_CD': "NOPAY_CD",
 'CLM_PMT_AMT': "PMT_AMT",
 'NCH_PRMRY_PYR_CLM_PD_AMT': "PRPAYAMT",
 'NCH_PRMRY_PYR_CD': "PRPAY_CD",
 'PRVDR_STATE_CD': "PRSTATE",
 'ORG_NPI_NUM': "ORGNPINM",
 'SRVC_LOC_NPI_NUM': "SRVC_LOC_NPI_NUM",
 'AT_PHYSN_UPIN': "AT_UPIN",
 'AT_PHYSN_NPI': "AT_NPI",
 'AT_PHYSN_SPCLTY_CD': "AT_PHYSN_SPCLTY_CD",
 'OP_PHYSN_NPI': "OP_NPI",
 'OP_PHYSN_SPCLTY_CD': "OP_PHYSN_SPCLTY_CD",
 'OT_PHYSN_NPI': "OT_NPI",
 'OT_PHYSN_SPCLTY_CD': "OT_PHYSN_SPCLTY_CD",
 'RNDRNG_PHYSN_NPI': "RNDRNG_PHYSN_NPI",
 'RNDRNG_PHYSN_SPCLTY_CD': "RNDRNG_PHYSN_SPCLTY_CD",
 'RFR_PHYSN_NPI': "RFR_PHYSN_NPI",
 'RFR_PHYSN_SPCLTY_CD': "RFR_PHYSN_SPCLTY_CD",
 'PTNT_DSCHRG_STUS_CD': "STUS_CD",
 'CLM_PPS_IND_CD': "PPS_IND",
 'CLM_TOT_CHRG_AMT': "TOT_CHRG",
 'PRNCPAL_DGNS_CD': "PRNCPAL_DGNS_CD",
 'ICD_DGNS_CD1': 'ICD_DGNS_CD1',
 'ICD_DGNS_CD2': 'ICD_DGNS_CD2',
 'ICD_DGNS_CD3': 'ICD_DGNS_CD3',
 'ICD_DGNS_CD4': 'ICD_DGNS_CD4',
 'ICD_DGNS_CD5': 'ICD_DGNS_CD5',
 'ICD_DGNS_CD6': 'ICD_DGNS_CD6',
 'ICD_DGNS_CD7': 'ICD_DGNS_CD7',
 'ICD_DGNS_CD8': 'ICD_DGNS_CD8',
 'ICD_DGNS_CD9': 'ICD_DGNS_CD9',
 'ICD_DGNS_CD10': 'ICD_DGNS_CD10',
 'ICD_DGNS_CD11': 'ICD_DGNS_CD11',
 'ICD_DGNS_CD12': 'ICD_DGNS_CD12',
 'ICD_DGNS_CD13': 'ICD_DGNS_CD13',
 'ICD_DGNS_CD14': 'ICD_DGNS_CD14',
 'ICD_DGNS_CD15': 'ICD_DGNS_CD15',
 'ICD_DGNS_CD16': 'ICD_DGNS_CD16',
 'ICD_DGNS_CD17': 'ICD_DGNS_CD17',
 'ICD_DGNS_CD18': 'ICD_DGNS_CD18',
 'ICD_DGNS_CD19': 'ICD_DGNS_CD19',
 'ICD_DGNS_CD20': 'ICD_DGNS_CD20',
 'ICD_DGNS_CD21': 'ICD_DGNS_CD21',
 'ICD_DGNS_CD22': 'ICD_DGNS_CD22',
 'ICD_DGNS_CD23': 'ICD_DGNS_CD23',
 'ICD_DGNS_CD24': 'ICD_DGNS_CD24',
 'ICD_DGNS_CD25': 'ICD_DGNS_CD25',
 'FST_DGNS_E_CD': 'FST_DGNS_E_CD',
 'ICD_DGNS_E_CD1': 'ICD_DGNS_E_CD1',
 'ICD_DGNS_E_CD2': 'ICD_DGNS_E_CD2',
 'ICD_DGNS_E_CD3': 'ICD_DGNS_E_CD3',
 'ICD_DGNS_E_CD4': 'ICD_DGNS_E_CD4',
 'ICD_DGNS_E_CD5': 'ICD_DGNS_E_CD5',
 'ICD_DGNS_E_CD6': 'ICD_DGNS_E_CD6',
 'ICD_DGNS_E_CD7': 'ICD_DGNS_E_CD7',
 'ICD_DGNS_E_CD8': 'ICD_DGNS_E_CD8',
 'ICD_DGNS_E_CD9': 'ICD_DGNS_E_CD9',
 'ICD_DGNS_E_CD10': 'ICD_DGNS_E_CD10',
 'ICD_DGNS_E_CD11': 'ICD_DGNS_E_CD11',
 'ICD_DGNS_E_CD12': 'ICD_DGNS_E_CD12',
 'CLM_HHA_LUPA_IND_CD': "LUPAIND",
 'CLM_HHA_RFRL_CD': "HHA_RFRL",
 'CLM_HHA_TOT_VISIT_CNT': "VISITCNT",
 'CLM_ADMSN_DT': "HHSTRTDT",
 'DOB_DT': "DOB_DT",
 'GNDR_CD': "GNDR_CD",
 'BENE_RACE_CD': "RACE_CD",
 'BENE_CNTY_CD': "CNTY_CD",
 'BENE_STATE_CD': "STATE_CD",
 'CWF_BENE_MDCR_STUS_CD': "CWF_BENE_MDCR_STUS_CD",
 'CLM_QUERY_CD': "QUERY_CD",
 'FI_CLM_ACTN_CD': "ACTIONCD",
 'CLM_MCO_PD_SW': "MCOPDSW",
 'NCH_BENE_DSCHRG_DT': "DSCHRGDT",
 'CLM_TRTMT_AUTHRZTN_NUM': "CLM_TRTMT_AUTHRZTN_NUM",
 'CLM_PRCR_RTRN_CD': "CLM_PRCR_RTRN_CD",
 'CLM_NEXT_GNRTN_ACO_IND_CD1': 'CLM_NEXT_GNRTN_ACO_IND_CD1',
 'CLM_NEXT_GNRTN_ACO_IND_CD2': 'CLM_NEXT_GNRTN_ACO_IND_CD2',
 'CLM_NEXT_GNRTN_ACO_IND_CD3': 'CLM_NEXT_GNRTN_ACO_IND_CD3',
 'CLM_NEXT_GNRTN_ACO_IND_CD4': 'CLM_NEXT_GNRTN_ACO_IND_CD4',
 'CLM_NEXT_GNRTN_ACO_IND_CD5': 'CLM_NEXT_GNRTN_ACO_IND_CD5',
 'ACO_ID_NUM': 'ACO_ID_NUM'}
