from pyspark.sql.types import StructType, StructField, StringType, IntegerType, LongType, DoubleType

snfBaseSchema = StructType([
    StructField('DESY_SORT_KEY', IntegerType(), True), 
    StructField('CLAIM_NO', IntegerType(), True), 
    StructField('PRVDR_NUM', StringType(), True), 
    StructField('CLM_THRU_DT', IntegerType(), True), 
    StructField('NCH_NEAR_LINE_REC_IDENT_CD', StringType(), True), 
    StructField('NCH_CLM_TYPE_CD', IntegerType(), True), 
    StructField('CLAIM_QUERY_CODE', IntegerType(), True), 
    StructField('CLM_FAC_TYPE_CD', IntegerType(), True), 
    StructField('CLM_SRVC_CLSFCTN_TYPE_CD', IntegerType(), True), 
    StructField('CLM_FREQ_CD', StringType(), True), 
    StructField('FI_NUM', IntegerType(), True), 
    StructField('CLM_MDCR_NON_PMT_RSN_CD', StringType(), True), 
    StructField('CLM_PMT_AMT', StringType(), True), 
    StructField('NCH_PRMRY_PYR_CLM_PD_AMT', DoubleType(), True), 
    StructField('NCH_PRMRY_PYR_CD', StringType(), True), 
    StructField('FI_CLM_ACTN_CD', IntegerType(), True), 
    StructField('PRVDR_STATE_CD', StringType(), True), 
    StructField('ORG_NPI_NUM', IntegerType(), True), 
    StructField('AT_PHYSN_UPIN', IntegerType(), True), 
    StructField('AT_PHYSN_NPI', IntegerType(), True), 
    StructField('AT_PHYSN_SPCLTY_CD', IntegerType(), True), 
    StructField('OP_PHYSN_UPIN', IntegerType(), True), 
    StructField('OP_PHYSN_NPI', IntegerType(), True), 
    StructField('OP_PHYSN_SPCLTY_CD', IntegerType(), True), 
    StructField('OT_PHYSN_UPIN', IntegerType(), True), 
    StructField('OT_PHYSN_NPI', IntegerType(), True), 
    StructField('OT_PHYSN_SPCLTY_CD', IntegerType(), True), 
    StructField('RNDRNG_PHYSN_NPI', IntegerType(), True), 
    StructField('RNDRNG_PHYSN_SPCLTY_CD', IntegerType(), True),
    StructField('CLM_MCO_PD_SW', IntegerType(), True), 
    StructField('PTNT_DSCHRG_STUS_CD', IntegerType(), True), 
    StructField('CLM_PPS_IND_CD', IntegerType(), True), 
    StructField('CLM_TOT_CHRG_AMT', DoubleType(), True), 
    StructField('CLM_ADMSN_DT', IntegerType(), True), 
    StructField('CLM_IP_ADMSN_TYPE_CD', IntegerType(), True),
    StructField('CLM_SRC_IP_ADMSN_CD', IntegerType(), True), 
    StructField('NCH_PTNT_STATUS_IND_CD', StringType(), True), 
    StructField('NCH_BENE_IP_DDCTBL_AMT', DoubleType(), True), 
    StructField('NCH_BENE_PTA_COINSRNC_LBLTY_AM', DoubleType(), True), 
    StructField('NCH_BENE_BLOOD_DDCTBL_LBLTY_AM', DoubleType(), True), 
    StructField('NCH_IP_NCVRD_CHRG_AMT', DoubleType(), True), 
    StructField('CLM_PPS_CPTL_FSP_AMT', DoubleType(), True), 
    StructField('CLM_PPS_CPTL_OUTLIER_AMT', DoubleType(), True), 
    StructField('CLM_PPS_CPTL_DSPRPRTNT_SHR_AMT', DoubleType(), True), 
    StructField('CLM_PPS_CPTL_IME_AMT', DoubleType(), True), 
    StructField('CLM_PPS_CPTL_EXCPTN_AMT', DoubleType(), True), 
    StructField('CLM_PPS_OLD_CPTL_HLD_HRMLS_AMT', DoubleType(), True), 
    StructField('CLM_UTLZTN_DAY_CNT', IntegerType(), True), 
    StructField('BENE_TOT_COINSRNC_DAYS_CNT', IntegerType(), True), 
    StructField('CLM_NON_UTLZTN_DAYS_CNT', IntegerType(), True), 
    StructField('NCH_BLOOD_PNTS_FRNSHD_QTY', IntegerType(), True), 
    StructField('NCH_QLFYD_STAY_THRU_DT', IntegerType(), True), 
    StructField('NCH_VRFD_NCVRD_STAY_FROM_DT', IntegerType(), True), 
    StructField('NCH_VRFD_NCVRD_STAY_THRU_DT', IntegerType(), True), 
    StructField('NCH_BENE_MDCR_BNFTS_EXHTD_DT_I', IntegerType(), True), 
    StructField('NCH_BENE_DSCHRG_DT', IntegerType(), True), 
    StructField('CLM_DRG_CD', IntegerType(), True), 
    StructField('ADMTG_DGNS_CD', StringType(), True), 
    StructField('PRNCPAL_DGNS_CD', StringType(), True), 
    StructField('ICD_DGNS_CD1', StringType(), True), 
    StructField('ICD_DGNS_CD2', StringType(), True), 
    StructField('ICD_DGNS_CD3', StringType(), True), 
    StructField('ICD_DGNS_CD4', StringType(), True), 
    StructField('ICD_DGNS_CD5', StringType(), True), 
    StructField('ICD_DGNS_CD6', StringType(), True), 
    StructField('ICD_DGNS_CD7', StringType(), True), 
    StructField('ICD_DGNS_CD8', StringType(), True), 
    StructField('ICD_DGNS_CD9', StringType(), True), 
    StructField('ICD_DGNS_CD10', StringType(), True), 
    StructField('ICD_DGNS_CD11', StringType(), True), 
    StructField('ICD_DGNS_CD12', StringType(), True), 
    StructField('ICD_DGNS_CD13', StringType(), True), 
    StructField('ICD_DGNS_CD14', StringType(), True), 
    StructField('ICD_DGNS_CD15', StringType(), True), 
    StructField('ICD_DGNS_CD16', StringType(), True), 
    StructField('ICD_DGNS_CD17', StringType(), True), 
    StructField('ICD_DGNS_CD18', StringType(), True), 
    StructField('ICD_DGNS_CD19', StringType(), True), 
    StructField('ICD_DGNS_CD20', StringType(), True), 
    StructField('ICD_DGNS_CD21', StringType(), True), 
    StructField('ICD_DGNS_CD22', StringType(), True), 
    StructField('ICD_DGNS_CD23', StringType(), True), 
    StructField('ICD_DGNS_CD24', StringType(), True), 
    StructField('ICD_DGNS_CD25', StringType(), True), 
    StructField('FST_DGNS_E_CD', StringType(), True), 
    StructField('ICD_DGNS_E_CD1', StringType(), True), 
    StructField('ICD_DGNS_E_CD2', StringType(), True), 
    StructField('ICD_DGNS_E_CD3', StringType(), True),
    StructField('ICD_DGNS_E_CD4', StringType(), True), 
    StructField('ICD_DGNS_E_CD5', StringType(), True), 
    StructField('ICD_DGNS_E_CD6', StringType(), True), 
    StructField('ICD_DGNS_E_CD7', StringType(), True), 
    StructField('ICD_DGNS_E_CD8', StringType(), True), 
    StructField('ICD_DGNS_E_CD9', StringType(), True), 
    StructField('ICD_DGNS_E_CD10', StringType(), True), 
    StructField('ICD_DGNS_E_CD11', StringType(), True), 
    StructField('ICD_DGNS_E_CD12', StringType(), True), 
    StructField('ICD_PRCDR_CD1', StringType(), True), 
    StructField('PRCDR_DT1', IntegerType(), True), 
    StructField('ICD_PRCDR_CD2', StringType(), True), 
    StructField('PRCDR_DT2', IntegerType(), True), 
    StructField('ICD_PRCDR_CD3', StringType(), True), 
    StructField('PRCDR_DT3', IntegerType(), True), 
    StructField('ICD_PRCDR_CD4', StringType(), True), 
    StructField('PRCDR_DT4', IntegerType(), True), 
    StructField('ICD_PRCDR_CD5', StringType(), True), 
    StructField('PRCDR_DT5', IntegerType(), True), 
    StructField('ICD_PRCDR_CD6', StringType(), True), 
    StructField('PRCDR_DT6', IntegerType(), True), 
    StructField('ICD_PRCDR_CD7', StringType(), True), 
    StructField('PRCDR_DT7', IntegerType(), True), 
    StructField('ICD_PRCDR_CD8', StringType(), True), 
    StructField('PRCDR_DT8', IntegerType(), True), 
    StructField('ICD_PRCDR_CD9', StringType(), True), 
    StructField('PRCDR_DT9', IntegerType(), True), 
    StructField('ICD_PRCDR_CD10', StringType(), True), 
    StructField('PRCDR_DT10', IntegerType(), True), 
    StructField('ICD_PRCDR_CD11', StringType(), True), 
    StructField('PRCDR_DT11', IntegerType(), True), 
    StructField('ICD_PRCDR_CD12', StringType(), True), 
    StructField('PRCDR_DT12', IntegerType(), True), 
    StructField('ICD_PRCDR_CD13', StringType(), True), 
    StructField('PRCDR_DT13', IntegerType(), True), 
    StructField('ICD_PRCDR_CD14', StringType(), True), 
    StructField('PRCDR_DT14', IntegerType(), True), 
    StructField('ICD_PRCDR_CD15', StringType(), True), 
    StructField('PRCDR_DT15', IntegerType(), True), 
    StructField('ICD_PRCDR_CD16', StringType(), True), 
    StructField('PRCDR_DT16', IntegerType(), True),
    StructField('ICD_PRCDR_CD17', StringType(), True), 
    StructField('PRCDR_DT17', IntegerType(), True), 
    StructField('ICD_PRCDR_CD18', StringType(), True), 
    StructField('PRCDR_DT18', IntegerType(), True), 
    StructField('ICD_PRCDR_CD19', StringType(), True), 
    StructField('PRCDR_DT19', IntegerType(), True), 
    StructField('ICD_PRCDR_CD20', StringType(), True), 
    StructField('PRCDR_DT20', IntegerType(), True), 
    StructField('ICD_PRCDR_CD21', StringType(), True), 
    StructField('PRCDR_DT21', IntegerType(), True), 
    StructField('ICD_PRCDR_CD22', StringType(), True), 
    StructField('PRCDR_DT22', IntegerType(), True), 
    StructField('ICD_PRCDR_CD23', StringType(), True), 
    StructField('PRCDR_DT23', IntegerType(), True), 
    StructField('ICD_PRCDR_CD24', StringType(), True), 
    StructField('PRCDR_DT24', IntegerType(), True), 
    StructField('ICD_PRCDR_CD25', StringType(), True), 
    StructField('PRCDR_DT25', IntegerType(), True), 
    StructField('DOB_DT', IntegerType(), True), 
    StructField('GNDR_CD', IntegerType(), True), 
    StructField('BENE_RACE_CD', IntegerType(), True), 
    StructField('BENE_CNTY_CD', StringType(), True), 
    StructField('BENE_STATE_CD', StringType(), True), 
    StructField('CWF_BENE_MDCR_STUS_CD', IntegerType(), True),
    StructField('CLM_TRTMT_AUTHRZTN_NUM', IntegerType(), True),
    StructField('CLM_PRCR_RTRN_CD', IntegerType(), True), 
    StructField('NCH_PROFNL_CMPNT_CHRG_AMT', DoubleType(), True), 
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD1', IntegerType(), True), 
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD2', IntegerType(), True), 
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD3', IntegerType(), True), 
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD4', IntegerType(), True), 
    StructField('CLM_NEXT_GNRTN_ACO_IND_CD5', IntegerType(), True), 
    StructField('ACO_ID_NUM', IntegerType(), True)])

snfBaseLongToShortXW = {'DESY_SORT_KEY':"DSYSRTKY",
 'CLAIM_NO': "CLAIMNO",
 'PRVDR_NUM': "PROVIDER",
 'CLM_THRU_DT': "THRU_DT",
 'NCH_NEAR_LINE_REC_IDENT_CD': "RIC_CD",
 'NCH_CLM_TYPE_CD': "CLM_TYPE",
 'CLAIM_QUERY_CODE': "QUERY_CD",
 'CLM_FAC_TYPE_CD': "FAC_TYPE",
 'CLM_SRVC_CLSFCTN_TYPE_CD': "TYPESRVC",
 'CLM_FREQ_CD': "FREQ_CD",
 'FI_NUM': "FI_NUM",
 'CLM_MDCR_NON_PMT_RSN_CD': "NOPAY_CD",
 'CLM_PMT_AMT': "PMT_AMT",
 'NCH_PRMRY_PYR_CLM_PD_AMT': "PRPAYAMT",
 'NCH_PRMRY_PYR_CD': "PRPAY_CD",
 'FI_CLM_ACTN_CD': "ACTIONCD",
 'PRVDR_STATE_CD': "PRSTATE",
 'ORG_NPI_NUM': "ORGNPINM",
 'AT_PHYSN_UPIN': "AT_UPIN",
 'AT_PHYSN_NPI': "AT_NPI",
 'AT_PHYSN_SPCLTY_CD': "AT_PHYSN_SPCLTY_CD",
 'OP_PHYSN_UPIN': "OP_UPIN",
 'OP_PHYSN_NPI': "OP_NPI",
 'OP_PHYSN_SPCLTY_CD': "OP_PHYSN_SPCLTY_CD",
 'OT_PHYSN_UPIN': "OT_UPIN",
 'OT_PHYSN_NPI': "OT_NPI",
 'OT_PHYSN_SPCLTY_CD': "OT_PHYSN_SPCLTY_CD",
 'RNDRNG_PHYSN_NPI': "RNDRNG_PHYSN_NPI",
 'RNDRNG_PHYSN_SPCLTY_CD': "RNDRNG_PHYSN_SPCLTY_CD",
 'CLM_MCO_PD_SW': "MCOPDSW",
 'PTNT_DSCHRG_STUS_CD': "STUS_CD",
 'CLM_PPS_IND_CD': "PPS_IND",
 'CLM_TOT_CHRG_AMT': "TOT_CHRG",
 'CLM_ADMSN_DT': "ADMSN_DT",
 'CLM_IP_ADMSN_TYPE_CD': "TYPE_ADM",
 'CLM_SRC_IP_ADMSN_CD': "SRC_ADMS",
 'NCH_PTNT_STATUS_IND_CD': "PTNTSTUS",
 'NCH_BENE_IP_DDCTBL_AMT': "DED_AMT",
 'NCH_BENE_PTA_COINSRNC_LBLTY_AM': "COIN_AMT",
 'NCH_BENE_BLOOD_DDCTBL_LBLTY_AM': "BLDDEDAM",
 'NCH_IP_NCVRD_CHRG_AMT': "NCCHGAMT",
 'CLM_PPS_CPTL_FSP_AMT': "CPTL_FSP",
 'CLM_PPS_CPTL_OUTLIER_AMT': "CPTLOUTL",
 'CLM_PPS_CPTL_DSPRPRTNT_SHR_AMT': "DISP_SHR",
 'CLM_PPS_CPTL_IME_AMT': "IME_AMT",
 'CLM_PPS_CPTL_EXCPTN_AMT': "CPTL_EXP",
 'CLM_PPS_OLD_CPTL_HLD_HRMLS_AMT': "HLDHRMLS",
 'CLM_UTLZTN_DAY_CNT': "UTIL_DAY",
 'BENE_TOT_COINSRNC_DAYS_CNT': "COIN_DAY",
 'CLM_NON_UTLZTN_DAYS_CNT': "NUTILDAY",
 'NCH_BLOOD_PNTS_FRNSHD_QTY': "BLDFRNSH",
 'NCH_QLFYD_STAY_THRU_DT': "QLFYTHRU",
 'NCH_VRFD_NCVRD_STAY_FROM_DT': "NCOVFROM",
 'NCH_VRFD_NCVRD_STAY_THRU_DT': "NCOVTHRU",
 'NCH_BENE_MDCR_BNFTS_EXHTD_DT_I': "EXHST_DT",
 'NCH_BENE_DSCHRG_DT': "DSCHRGDT",
 'CLM_DRG_CD': "DRG_CD",
 'ADMTG_DGNS_CD': "ADMTG_DGNS_CD",
 'PRNCPAL_DGNS_CD': "PRNCPAL_DGNS_CD",
 'ICD_DGNS_CD1': 'ICD_DGNS_CD1',
 'ICD_DGNS_CD2': 'ICD_DGNS_CD2',
 'ICD_DGNS_CD3': 'ICD_DGNS_CD3',
 'ICD_DGNS_CD4': 'ICD_DGNS_CD4',
 'ICD_DGNS_CD5': 'ICD_DGNS_CD5',
 'ICD_DGNS_CD6': 'ICD_DGNS_CD6',
 'ICD_DGNS_CD7': 'ICD_DGNS_CD7',
 'ICD_DGNS_CD8': 'ICD_DGNS_CD8',
 'ICD_DGNS_CD9': 'ICD_DGNS_CD9',
 'ICD_DGNS_CD10': 'ICD_DGNS_CD10',
 'ICD_DGNS_CD11': 'ICD_DGNS_CD11',
 'ICD_DGNS_CD12': 'ICD_DGNS_CD12',
 'ICD_DGNS_CD13': 'ICD_DGNS_CD13',
 'ICD_DGNS_CD14': 'ICD_DGNS_CD14',
 'ICD_DGNS_CD15': 'ICD_DGNS_CD15',
 'ICD_DGNS_CD16': 'ICD_DGNS_CD16',
 'ICD_DGNS_CD17': 'ICD_DGNS_CD17',
 'ICD_DGNS_CD18': 'ICD_DGNS_CD18',
 'ICD_DGNS_CD19': 'ICD_DGNS_CD19',
 'ICD_DGNS_CD20': 'ICD_DGNS_CD20',
 'ICD_DGNS_CD21': 'ICD_DGNS_CD21',
 'ICD_DGNS_CD22': 'ICD_DGNS_CD22',
 'ICD_DGNS_CD23': 'ICD_DGNS_CD23',
 'ICD_DGNS_CD24': 'ICD_DGNS_CD24',
 'ICD_DGNS_CD25': 'ICD_DGNS_CD25',
 'FST_DGNS_E_CD': 'FST_DGNS_E_CD',
 'ICD_DGNS_E_CD1': 'ICD_DGNS_E_CD1',
 'ICD_DGNS_E_CD2': 'ICD_DGNS_E_CD2',
 'ICD_DGNS_E_CD3': 'ICD_DGNS_E_CD3',
 'ICD_DGNS_E_CD4': 'ICD_DGNS_E_CD4',
 'ICD_DGNS_E_CD5': 'ICD_DGNS_E_CD5',
 'ICD_DGNS_E_CD6': 'ICD_DGNS_E_CD6',
 'ICD_DGNS_E_CD7': 'ICD_DGNS_E_CD7',
 'ICD_DGNS_E_CD8': 'ICD_DGNS_E_CD8',
 'ICD_DGNS_E_CD9': 'ICD_DGNS_E_CD9',
 'ICD_DGNS_E_CD10': 'ICD_DGNS_E_CD10',
 'ICD_DGNS_E_CD11': 'ICD_DGNS_E_CD11',
 'ICD_DGNS_E_CD12': 'ICD_DGNS_E_CD12',
 'ICD_PRCDR_CD1': 'ICD_PRCDR_CD1',
 'PRCDR_DT1': 'PRCDR_DT1',
 'ICD_PRCDR_CD2': 'ICD_PRCDR_CD2',
 'PRCDR_DT2': 'PRCDR_DT2',
 'ICD_PRCDR_CD3': 'ICD_PRCDR_CD3',
 'PRCDR_DT3': 'PRCDR_DT3',
 'ICD_PRCDR_CD4': 'ICD_PRCDR_CD4',
 'PRCDR_DT4':'PRCDR_DT4',
 'ICD_PRCDR_CD5': 'ICD_PRCDR_CD5',
 'PRCDR_DT5': 'PRCDR_DT5',
 'ICD_PRCDR_CD6': 'ICD_PRCDR_CD6',
 'PRCDR_DT6': 'PRCDR_DT6',
 'ICD_PRCDR_CD7': 'ICD_PRCDR_CD7',
 'PRCDR_DT7': 'PRCDR_DT7',
 'ICD_PRCDR_CD8': 'ICD_PRCDR_CD8',
 'PRCDR_DT8': 'PRCDR_DT8',
 'ICD_PRCDR_CD9': 'ICD_PRCDR_CD9',
 'PRCDR_DT9': 'PRCDR_DT9',
 'ICD_PRCDR_CD10': 'ICD_PRCDR_CD10',
 'PRCDR_DT10': 'PRCDR_DT10',
 'ICD_PRCDR_CD11': 'ICD_PRCDR_CD11',
 'PRCDR_DT11': 'PRCDR_DT11',
 'ICD_PRCDR_CD12': 'ICD_PRCDR_CD12',
 'PRCDR_DT12': 'PRCDR_DT12',
 'ICD_PRCDR_CD13': 'ICD_PRCDR_CD13',
 'PRCDR_DT13': 'PRCDR_DT13',
 'ICD_PRCDR_CD14': 'ICD_PRCDR_CD14',
 'PRCDR_DT14':'PRCDR_DT14',
 'ICD_PRCDR_CD15': 'ICD_PRCDR_CD15',
 'PRCDR_DT15': 'PRCDR_DT15',
 'ICD_PRCDR_CD16': 'ICD_PRCDR_CD16',
 'PRCDR_DT16': 'PRCDR_DT16',
 'ICD_PRCDR_CD17': 'ICD_PRCDR_CD17',
 'PRCDR_DT17': 'PRCDR_DT17',
 'ICD_PRCDR_CD18': 'ICD_PRCDR_CD18',
 'PRCDR_DT18': 'PRCDR_DT18',
 'ICD_PRCDR_CD19': 'ICD_PRCDR_CD19',
 'PRCDR_DT19': 'PRCDR_DT19',
 'ICD_PRCDR_CD20': 'ICD_PRCDR_CD20',
 'PRCDR_DT20': 'PRCDR_DT20',
 'ICD_PRCDR_CD21': 'ICD_PRCDR_CD21',
 'PRCDR_DT21': 'PRCDR_DT21',
 'ICD_PRCDR_CD22': 'ICD_PRCDR_CD22',
 'PRCDR_DT22': 'PRCDR_DT22',
 'ICD_PRCDR_CD23': 'ICD_PRCDR_CD23',
 'PRCDR_DT23': 'PRCDR_DT23',
 'ICD_PRCDR_CD24': 'ICD_PRCDR_CD24',
 'PRCDR_DT24': 'PRCDR_DT24',
 'ICD_PRCDR_CD25': 'ICD_PRCDR_CD25',
 'PRCDR_DT25': 'PRCDR_DT25',
 'DOB_DT': 'DOB_DT',
 'GNDR_CD': 'GNDR_CD',
 'BENE_RACE_CD': 'BENE_RACE_CD',
 'BENE_CNTY_CD': 'BENE_CNTY_CD',
 'BENE_STATE_CD': 'BENE_STATE_CD',
 'CWF_BENE_MDCR_STUS_CD': 'CWF_BENE_MDCR_STUS_CD',
 'CLM_TRTMT_AUTHRZTN_NUM':  'CLM_TRTMT_AUTHRZTN_NUM',
 'CLM_PRCR_RTRN_CD': 'CLM_PRCR_RTRN_CD',
 'NCH_PROFNL_CMPNT_CHRG_AMT': 'NCH_PROFNL_CMPNT_CHRG_AMT',
 'CLM_NEXT_GNRTN_ACO_IND_CD1': 'CLM_NEXT_GNRTN_ACO_IND_CD1',
 'CLM_NEXT_GNRTN_ACO_IND_CD2': 'CLM_NEXT_GNRTN_ACO_IND_CD2',
 'CLM_NEXT_GNRTN_ACO_IND_CD3': 'CLM_NEXT_GNRTN_ACO_IND_CD3',
 'CLM_NEXT_GNRTN_ACO_IND_CD4': 'CLM_NEXT_GNRTN_ACO_IND_CD4',
 'CLM_NEXT_GNRTN_ACO_IND_CD5': 'CLM_NEXT_GNRTN_ACO_IND_CD5',
 'ACO_ID_NUM': 'ACO_ID_NUM'}
